export const LOGIN = "LOGIN";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTER = "REGISTER";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_ERROR = "SEND_OTP_ERROR";

export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";

export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";
export const VERIFY_ACCOUNT_REQUEST = "VERIFY_ACCOUNT_REQUEST";
export const VERIFY_ACCOUNT_ERROR = "VERIFY_ACCOUNT_ERROR";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const GET_PROFILE = "GET_PROFILE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const GET_ALL_TICKETS = "GET_ALL_TICKETS";
export const GET_BY_ID_TICKET = "GET_BY_ID_TICKET";
export const GET_TICKET_BY_QUERY = "GET_TICKET_BY_QUERY";
export const FILTER_TICKET = "FILTER_TICKET";

export const ADD_BOOKING = "ADD_BOOKING";
export const ADD_BOOKING_REQUEST = "ADD_BOOKING_REQUEST";
export const ADD_BOOKING_ERROR = "ADD_BOOKING_ERROR";

export const GET_BOOKING = "GET_BOOKING";

export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const MAKE_PAYMENT_REQUEST = "MAKE_PAYMENT_REQUEST";
export const MAKE_PAYMENT_ERROR = "MAKE_PAYMENT_ERROR";

export const GET_ALL_HISTORY = "GET_ALL_HISTORY";
export const FILTER_HISTORY = "FILTER_HISTORY";
export const SEARCH_HISTORY = "SEARCH_HISTORY";
