export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const SEARCH_EMAIL = "SEARCH_EMAIL";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_PROFILE = "GET_PROFILE";

export const GET_ALL_TICKETS = "GET_ALL_TICKETS";
export const GET_BY_ID_TICKET = "GET_BY_ID_TICKET";
export const GET_TICKET_BY_QUERY = "GET_TICKET_BY_QUERY";
export const FILTER_TICKET = "FILTER_TICKET";
